version: '3.5'
services:
  mysingboxconverter:
    build: .
    image: mysingboxconverter
    ports:
      - "127.0.0.1:45288:5000"
    networks:
      - subconverter

networks:
  subconverter:
    name: subconverter
    external: true
